aerial_robot_control_name: aerial_robot_control/nmpc_tilt_qd_servo_w_cog_end_dist/nmpc_controller

controller:
  nmpc:
    T_samp: 0.01  # 100 Hz  TODO: should be adjusted by main_rate
    T_horizon: 2.0  # seconds
    T_step: 0.1  # seconds

    # Hard constraints
    w_max: 6  # 1 rad/s ~ 57 deg/s
    w_min: -6

    v_max: 1
    v_min: -1

    thrust_max: 30 # N
    thrust_min: 0 # N

    a_max: 1.5708  # 30 degree ~ 0.5    1.5708 rad ~ 90 deg
    a_min: -1.5708

    # Cost function weights
    Qp_xy: 300
    Qp_z: 400
    Qv_xy: 10
    Qv_z: 10
    Qq_xy: 300
    Qq_z: 600
    Qw_xy: 5
    Qw_z: 5
    Qa: 1
    Rt: 1
    Rac_d: 250  # difference of ac

    # Slack constraint weights
    linear_slack_weight: 10
    quadratic_slack_weight: 100

    is_attitude_ctrl: false
    is_body_rate_ctrl: false

    is_print_physical_params: false
    is_debug: false

    # disturb_rej
    limit_fx: 5.0
    limit_fy: 5.0
    limit_fz: 5.0
    limit_mx: 1.0
    limit_my: 1.0
    limit_mz: 1.0

    i_gain_x: 0
    i_gain_y: 0
    i_gain_z: 5
    i_gain_roll: 0.0
    i_gain_pitch: 0.0
    i_gain_yaw: 0.0
