# .pre-commit-config.yaml
minimum_pre_commit_version: "3.5.0"
#default_language_version:
#  python: python3.11

repos:
  # Generic tidy-ups ----------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # 2024-10-07
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=10000]
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=auto]

  # Python --------------------------------------------------------------------
  - repo: https://github.com/psf/black
    rev: 23.11.0  # from the next version of black (24.1.0), it requires Python >3.8
    hooks:
      - id: black
        args: [--line-length=120]

  # C / C++ -------------------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.5
    hooks:
      - id: clang-format
        additional_dependencies: [clang==20.1.5]  # ensures matching binary

  # YAML --------------------------------------------------------------------
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
