# .pre-commit-config.yaml
minimum_pre_commit_version: "3.5.0"
#default_language_version:
#  python: python3.11

repos:
  # Generic tidy-ups ----------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0          # 2024-10-07
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [ --maxkb=10000 ]
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        args: [ --fix=auto ]

  # Python --------------------------------------------------------------------
  - repo: https://github.com/psf/black
    rev: 25.1.0          # 2025-01-29
    hooks:
      - id: black
        args: [ --line-length=120 ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3          # pin a recent ruff release
    hooks:
      - id: ruff
        args: [ --line-length=120, --output-format=github ]

  # C / C++ -------------------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.5
    hooks:
      - id: clang-format
        additional_dependencies: [ clang==20.1.5 ]   # ensures matching binary

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
