mpc_solver_name: aerial_robot_control::mpc_solver::TiltQdServoDistMdlMPCSolver
aerial_robot_control_name: aerial_robot_control/nmpc_controller/tilt_mt/servo_dist_nmpc

controller:
  alloc:
    type: 1    # 0: pseudo allocation, 1: heuristic allocation,
    ft_thresh: 1.0  # N

  nmpc:
    T_samp: 0.01    # 100 Hz  TODO: should be adjusted by main_rate
    T_horizon: 2.0  # in seconds
    T_step: 0.1     # in seconds

    # Hard constraints
    w_max: 6  # 1 rad/s ~ 57 deg/s
    w_min: -6

    v_max: 1
    v_min: -1

    thrust_max: 30 # N
    thrust_min: 0 # N

    a_max: 3.92699  # 180 + 45 degree ~ 0.5
    a_min: -3.92699

    # Cost function weights
    Qp_xy: 300
    Qp_z: 400
    Qv_xy: 10
    Qv_z: 10
    Qq_xy: 300
    Qq_z: 600
    Qw_xy: 5
    Qw_z: 5
    Qa: 2
    Rt: 2
    Rac_d: 250  # difference of ac

    # Slack constraint weights
    linear_slack_weight: 10
    quadratic_slack_weight: 100

    is_attitude_ctrl: false
    is_body_rate_ctrl: false

    is_print_phys_params: false
    is_debug: false
