# Sensor Fuser Loader
estimation:
  mhe:
    T_samp: 0.005  # 200 Hz  TODO: should be the same with IMU rate
    T_horizon: 0.1  # seconds
    T_step: 0.005  # seconds

    # arrival cost
    P_p: 0.1
    P_v: 0.1
    P_a_sf: 0.1
    P_q: 0.1
    P_omega: 0.1

    # noise sigma
    R_p: 0.001
    R_a_sf: 0.07
    R_q: 0.01
    R_omega: 0.008

    Q_w_a_sf: 0.1
    Q_w_omega: 0.1
