# I Term is always used and has higher priority than the other wrench estimation methods.
controller:
  i_term:
    # disturb_rej
    limit_fx: 5.0
    limit_fy: 5.0
    limit_fz: 5.0
    limit_mx: 1.0
    limit_my: 1.0
    limit_mz: 1.0

    i_gain_x: 0  # 1
    i_gain_y: 0  # 1
    i_gain_z: 1
    i_gain_roll: 0.0  # 0.3
    i_gain_pitch: 0.0  # 0.3
    i_gain_yaw: 0.0  # 0.3