wrench_estimator_name: aerial_robot_control::WrenchEstMomentum

controller:
  if_use_est_wrench_4_control: true

  wrench_est:
    # mode switch
    calib_duration_t: 5.0  # seconds
    lin_vel_threshold: [0.2, 0.2, 0.2]  # [x, y, z] m/s
    ang_vel_threshold: [0.3, 0.3, 0.3]  # [x, y, z] rad/s

    # overall limit
    ext_force_limit: [10, 10, 10]  # N
    ext_torque_limit: [5, 5, 5]  # Nm

    # small noise: use sigmoid function for a threshold
    thresh_force: 0.6  # N
    thresh_torque: 0.3  # Nm
    steepness_force: 10.0
    steepness_torque: 10.0

  momentum_observer:
    momentum_observer_force_weight: 3.0
    momentum_observer_torque_weight: 1.5
