@startuml
'https://plantuml.com/sequence-diagram

' Legend
' ->> means inner communication via variables
'-> means outer communication via ROS topics

'for nested boxes
!pragma teoz true

autonumber

box Laptop #Khaki
participant RViz
participant Terminal
end box

box "Onboard PC\n(VIM 4 + NMPC Control)" #LightGreen
participant "Planning" as Nav
participant "Control" as Ctl
participant "Estimator" as Est
end box

box Gazebo (Laptop) #Aliceblue

    box "     MCU\n(STM32 H7)" #LightBlue
    participant "Spinal/Control_Spawner" as Spinal
    end box

    box Body  #LightGray
    participant "ESC&Servo" as ESC
    end box

end box

Est ->> Est: 200Hz

loop 100Hz
    Est ->> Ctl: estimator_->getState()
end loop

loop 50Hz
    Nav ->> Ctl: Traj
end loop


loop 100Hz
    Ctl -> Spinal: Thrust and Servo Angles
end loop
Spinal -> ESC: DShot & Angle

@enduml
